# Generated by Django 5.0.6 on 2024-05-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blogs'),
        ),
    ]
